version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: recipes

  backend:
    build:
      context: .
    ports:
      - 8000:8000
    command: bash -c "
      ./wait-for-postgres.sh db &&
      python manage.py migrate &&
      python manage.py loaddata recipes.json &&
      python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db